version: 0.2

env:
  variables:
    CODE_CLIMATE_REPORTER_ID: ""
    CODECOV_TOKEN: ""
    GIT_BRANCH: "master"

phases:

  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - echo Runninging code quality tools.
      - docker build --build-arg ENV_CONFIGURATION=production --build-arg CODE_CLIMATE_REPORTER_ID=$CODE_CLIMATE_REPORTER_ID --build-arg CODECOV_TOKEN=$CODECOV_TOKEN --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION --build-arg GIT_BRANCH=${GIT_BRANCH} -f Dockerfile_quality .
      - echo Code Quality check is passed
